date_default_timezone_set('Asia/Jakarta');
include "function.php";
echo color("red"," ===========================\n");
echo color("red","| Claim Voucher Gojek|\n");
echo color("red","| Auto create Gojek X Redeem voucher |\n");
echo color("red","| Creator : Calon Sarjana            |\n");
echo color("red","| github: kumpulanremaja |\n");
echo color("red","| fanspage :4kumpulanremaja|\n");
echo color("red","| Creator : kumpulanremaja.com          |\n");
echo "| Version : Premium X pertalite      |\n";
echo "| Time    :".date('[d-m-Y] [H:i:s]')."   |\n";
echo " ===========================\n";
@@ -184,4 +187,4 @@
         }
//  }

// echo change()."\n"; 
// echo change()."\n";
